const USER_EMAIL_HEADER = 'X-User-Email';
const USER_PASSWORD_HEADER = 'X-User-Password';
const USER_JWT_TOKEN_HEADER = 'X-User-Token';
const USER_JWT_TOKEN_EXPIRATION_HEADER = 'X-User-Token-Expiration';

const ERROR_TAG = 'X-Error-Message';
const API_KEY_HEADER = 'X-Api-Key';

export {
  USER_EMAIL_HEADER,
  USER_PASSWORD_HEADER,
  USER_JWT_TOKEN_HEADER,
  USER_JWT_TOKEN_EXPIRATION_HEADER,
  ERROR_TAG,
  API_KEY_HEADER,
};
